# Generated by Django 3.2.9 on 2022-01-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='state',
        ),
    ]
