# Generated by Django 3.2.9 on 2021-12-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
