# Generated by Django 3.2.9 on 2021-12-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
