# Generated by Django 3.2.9 on 2021-12-31 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20211231_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
